/**********************************************************************
 * Extern for React3
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var React3 = {
  "propTypes": {
    "context": {
      "isRequired": function () {}
    },
    "width": function () {},
    "height": function () {},
    "children": {
      "isRequired": function () {}
    },
    "canvasStyle": {
      "isRequired": function () {}
    },
    "customRenderer": {
      "isRequired": function () {}
    },
    "gammaInput": {
      "isRequired": function () {}
    },
    "gammaOutput": {
      "isRequired": function () {}
    },
    "sortObjects": {
      "isRequired": function () {}
    },
    "mainCamera": {
      "isRequired": function () {}
    },
    "onAnimate": {
      "isRequired": function () {}
    },
    "clearColor": {
      "isRequired": function () {}
    },
    "shadowMapEnabled": {
      "isRequired": function () {}
    },
    "shadowMapType": {
      "isRequired": function () {}
    },
    "shadowMapCullFace": {
      "isRequired": function () {}
    },
    "shadowMapDebug": {
      "isRequired": function () {}
    },
    "pixelRatio": {
      "isRequired": function () {}
    },
    "antialias": {
      "isRequired": function () {}
    },
    "canvasRef": {
      "isRequired": function () {}
    }
  },
  "defaultProps": {
    "context": {}
  },
  "findTHREEObject": function () {},
  "eventDispatcher": {}
};
React3.prototype = {
  "isReactComponent": function () {},
  "setState": function () {},
  "forceUpdate": function () {}
};
/**********************************************************************
 * End Generated Extern for React3
/**********************************************************************/
